### ISSUE TITLE
When resizing the screen tiles sometimes get messed up

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#14]
The library we use seems to get the size of the tiles before some of them are resized by media queries, which breaks the layout it calculated.

**Comment by jviereck** [comment]
Why are we doing the tile resizing using JS and not using media queries / CSS?

**Comment by freaktechnik** [comment]
@jviereck That's done in media queries, problem is, the grid generator can't reliable wait long enough for the resize to have happened when he recalculates the layout with just the window resize event.
EDIT: removed traces of my incapability to read
EDIT2: I've also tried using the media query listeners in JS with no luck
