### ISSUE TITLE
Problem starting local server

### ISSUE THREAD

**Issue by jviereck** [mozillacommunitych/mozilla.ch#15]
Hi there,
following the instructions listed in the README.md file to start local dev server I get the error here:

https://gist.github.com/jviereck/d896c0eee791c017d1b8

Any ideas what is going wrong?

lg Julian

**Comment by freaktechnik** [comment]
http://stackoverflow.com/questions/24251793/warning-date-default-timezone-get-installing-symfony
TL;DR: php.ini hat keine timezone definiert
