### ISSUE TITLE
Contribute thing points to l10n.mozilla.org in english

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#16]
Shouldn't the left bottom contribute thing link to somewhere else than l10n.mozilla.org for english?

**Comment by MichaelKohler** [comment]
yeah, seems like it should point to mozilla.org/contribute or something similar?

**Comment by freaktechnik** [comment]
Yup. We should probably make the url localizeable?

**Comment by MichaelKohler** [comment]
Yes, we probably also want to point to the different communities that do translations and give visitors a chance to contribute in their own locale.
