### ISSUE TITLE
mozilla.ch domain + community IT finish

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#17]

**Comment by freaktechnik** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1130862

**Comment by MichaelKohler** [comment]
Updated the bug and contacted the current owner.

**Comment by MichaelKohler** [comment]
Asked about SSL and info@mozilla.ch

**Comment by MichaelKohler** [comment]
we're currently blocked on Pierros' feedback. let me see what I can do.

**Comment by MichaelKohler** [comment]
domain is being transfered to Mozilla, will check with Community IT on the status of the infrastructure

**Comment by MichaelKohler** [comment]
we will need a docker container for community it -> @colinfrei do you already have something we could use?

**Comment by MichaelKohler** [comment]
currently running on my server, but it's online :)

**Comment by J0WI** [comment]
http://mozilla.ch/ points now to @MichaelKohler's server. \o/
The performance is terrible, when the page isn't cached and we still have no https.

**Comment by MichaelKohler** [comment]
Will talk to Community IT during the next Work Week about this.. this will happen the week of Dec 7

**Comment by MichaelKohler** [comment]
We have a "GO" for the pilot phase for Mesosphere (or whatever they are using now).

**Comment by MichaelKohler** [comment]
According to https://github.com/mozillach/mozilla.ch/issues/60 we're finished here. Let me get in touch with the necessary people to get this deployed.

**Comment by MichaelKohler** [comment]
TODO here:
- Get in touch with the team
- Ask about Mozillians API key (how will this be handled?)
- Ask about Deployment from our side
- Ask about timeline (and let point mozilla.ch to 46.101.156.191 in case it's too long)

Repo with the docker image: https://github.com/mozillach/mozilla.ch-docker

**Comment by MichaelKohler** [comment]
"20:57:55 @yalam96 mkohler, can i get a link to the repo?
20:58:11 <mkohler> yalam96: https://github.com/mozillach/mozilla.ch-docker
21:01:11 @yalam96 mkohler, can you also email me your mozillians api key
21:04:49 <mkohler> yalam96: sent
21:05:40 <mkohler> yalam96: the other question then would be on how we would push updates
21:09:57 @yalam96 mkohler, right now it will have to be manual since we may move to a different paas soon
21:10:30 <mkohler> meaning manually by you guys or could we do that as well?
21:26:38 @yalam96 would be me"

**Comment by MichaelKohler** [comment]
Looks like the API key is no problem. Regarding timeline: Seems like we can do  this pretty fast, but we need to fix a few failures first ;) It's currently up here: https://mozillach.paas.mozilla.community/

Let me file a few followup bugs in the docker repo.

**Comment by MichaelKohler** [comment]
Now covered by https://github.com/mozillach/participation/issues/16
