### ISSUE TITLE
calender symbol character is not encoded

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#19]
app/Resources/public/less/index.less:157

``` css
content: "";
```

Spec: "<string> value, non-latin characters must be encoded"

@freaktechnik I fixed this in #18, but I'm using the official calender icon instead of this unstandardised one.

**Comment by freaktechnik** [comment]
I just copied the value from mozilla, though I forgot to convert it back to the encoded value.
