### ISSUE TITLE
missing mozillians.api parameters breaks local development

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#21]
Some parameters are missing. Please provide them.
mozillians.api_app_name (null): 
mozillians.api_key (null): 
mozillians.group_names (switzerland): 

Without these arguments you will get an error:

An exception has been thrown during the rendering of a template ("Client error response
[status code] 401
[reason phrase] UNAUTHORIZED
[url] https://mozillians.org/api/v1/users?app_name&app_key&groups=switzerland") in index.html.twig at line 73.

500 Internal Server Error - Twig_Error_Runtime
1 linked Exception:
ClientErrorResponseException »

**Comment by colinfrei** [comment]
Will need to check if they're around and display default content if not.

**Comment by J0WI** [comment]
Thanks!
