### ISSUE TITLE
Code cleanup (Less, index.html.twig?, ...)

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#22]

**Comment by freaktechnik** [comment]
Well, the only file we should clean up is index.less and maybe split it up in multiple files. the other ones are more or less the same, except for a removed font definition.

**Comment by J0WI** [comment]
Is this bug just to have nice code or for performance improvements, too?
Most pictures are replaced with SVGs now. This reduce bandwidth usage a lot, especially when we have gzip compression on the server.
I have a very slow rendering on mobile devices (even on Firefox OS) and it looks horrible before the JavaScript is executed. Maybe we can improve that part a bit.

**Comment by MichaelKohler** [comment]
EVERYTHING :D

**Comment by freaktechnik** [comment]
If we set the tile position to relative (As it would be from the mozilla.org styles) by default the rendering would look a bit less terrible, but we'd still get a reflow from the grid javascript doing its magic.

**Comment by MichaelKohler** [comment]
sounds good to me
