### ISSUE TITLE
Link to external blogposts

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#24]
I just removed the "external blogposts tile" from issue #9. I think a tile is too complicated to maintain since we won't have an up-to-date blogpost all the time. Do you have any idea how to promote otherwise?

**Comment by J0WI** [comment]
We could use RSS-Feeds or similar.
Or we just create static tiles for topics like http://www.firefox10.org/

**Comment by MichaelKohler** [comment]
For topics like firefox10.org we can always use the "Campaign" tile (currently "Firefox Hello"). If we don't have a campaign at some point, we could move the most recent MozillaCH related blog post there.

**Comment by MichaelKohler** [comment]
Let's use the Campaign Tile for important blog posts.
