### ISSUE TITLE
mozillians.org Pictures + Info to everybody

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#26]
- Inform everybody that they'll show up on the website
- Ask them to upload pictures to Gravatar with their real face if possible

**Comment by ioana-chiorean** [comment]
Also worth considering to link their profile from mozillians.org behind their pic ( and will be nice to be not empty profiles :D)

**Comment by colinfrei** [comment]
I'd love to do that, unfortunately we don't get that information through the Mozillians API.

**Comment by colinfrei** [comment]
also, for the record, the mozillians API bug to get access: https://bugzilla.mozilla.org/show_bug.cgi?id=1148741

Our current access is a bit "unofficial"

**Comment by MichaelKohler** [comment]
I will send out a mail tonight. I think we need another group, since people might not be aware that their picture is shown on the website. And still having a switzerland group without ties to the website is needed. So I'll create a new group and send out a mail tonight.

**Comment by colinfrei** [comment]
I'm not sure an additional group is necessary - it seems like an unnecessary hurdle.
There is already an option in mozillians to decide if you want to share your info with community sites (though with our hacky way of showing images it's true that it's not obvious).

**Comment by MichaelKohler** [comment]
would that also mean that we're gonna ask everyone who wants another gravatar picture to leave the group?

**Comment by colinfrei** [comment]
Ideally we'll be able to fetch the picture directly from mozillians and don't need to do the workaround.

**Comment by ioana-chiorean** [comment]
Maybe Tasos or Nemo can help arouns with this?  I am totally || with this.. @MichaelKohler I think u have their contact ..

**Comment by freaktechnik** [comment]
We'll be able to fetch the picutres directly, based on each mozillian's privacy setting, with API v2, which isn't publicly available yet. It seems the public launch is being prepared, but I'd expect it to take a while, since they want to deprecate existing keys.

**Comment by MichaelKohler** [comment]
Just sent out the information to all "switzerland" group members on Mozillians.org and the mailing list.

**Comment by MichaelKohler** [comment]
we're now using v2, so this isn't a problem anymore
