### ISSUE TITLE
Padding for "Next Event" tile is wrong

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#27]
![screen shot 2015-04-05 at 03 37 38](https://cloud.githubusercontent.com/assets/330324/6995386/4ae6d8e4-db45-11e4-829b-947383bda223.png)

**Comment by J0WI** [comment]
Do we need a workaround for other browsers?

**Comment by MichaelKohler** [comment]
that's fine for me
