### ISSUE TITLE
No text shown for no events

### ISSUE THREAD

**Issue by ioana-chiorean** [mozillacommunitych/mozilla.ch#28]
Just to track it ( cc @MichaelKohler )
![screenshot 2015-04-05 17 13 22](https://cloud.githubusercontent.com/assets/1391451/6997297/6ce6b57a-dbbf-11e4-8407-0fa51323aa6c.png)

**Comment by freaktechnik** [comment]
Works perfectly fine in the dev preview, I wonder if there are any errors, @colinfrei?

**Comment by colinfrei** [comment]
"Fixed" - there was an issue with the SSL certificate. I'll debug more when we're on the community IT server, if the issue still occurs then. For now I've disabled SSL verification for reps.mozilla.org

**Comment by ioana-chiorean** [comment]
Verified as Fixed :dancer: 
![screenshot from 2015-04-06 11 58 56](https://cloud.githubusercontent.com/assets/1391451/7002518/bdde2cfc-dc54-11e4-836f-afbd7f4458ff.png)
