### ISSUE TITLE
Get Involved

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#3]
- below the tiles
- Initial text
- "L10N" and "Contact" tiles

**Comment by MichaelKohler** [comment]
https://github.com/mozillacommunitych/mozillach_playground/commit/d93ecf3368e326c83603f0c37f8bda5ec61b9009

**Comment by J0WI** [comment]
https://github.com/mozillacommunitych/mozillach_playground/pull/3

**Comment by freaktechnik** [comment]
Missing picture for "l10n" subsection
