### ISSUE TITLE
Calm down tiles

### ISSUE THREAD

**Issue by colinfrei** [mozillacommunitych/mozilla.ch#30]
Comparing our site to mozilla.org, ours seems a bit ... noisier? My first guess is that it's because we have a bunch more content. I wonder if we should make some of the tiles bigger (even if they don't say more than now) to make the page calmer.

Opinions and suggestions on which tiles should become bigger?

**Comment by colinfrei** [comment]
Also, maybe we should replace the tweet tile with just the text of the latest tweet. Privacy reasons have been mentioned before, but there's also a lot of stuff in that iframe.

**Comment by colinfrei** [comment]
I'd make _Firefox OS Apps aus der Schweiz_ larger and maybe remove some of the product specific tiles.

**Comment by freaktechnik** [comment]
:+1:

**Comment by MichaelKohler** [comment]
we should make everything larger that is specific to the Swiss community. sounds good to me. +1 for the tweet tile.. looks like we agree here, so let's do it :) 

Further the Involved Tile could probably be removed since we have the content right below. And maybe we can just have one Tweet tile with the latest tweet? If people want to follow us they'll click on that anyway and not the follow us tile.

The other tiles can be removed if we don't have enough space in my opinion.

**Comment by J0WI** [comment]
How about randomize more tiles, instead of removing them?
e.g. gear store, dev-edition, independent and privacy

**Comment by freaktechnik** [comment]
@J0WI: those are already randomized. But we will probably remove some spots to make space for bigger tiles. The nice thing about the random tiles, is that we can add and remove spots for them whenever we want.

**Comment by MichaelKohler** [comment]
Here are my suggestions, but not sure if that's still not too much:

![mozillach1](https://cloud.githubusercontent.com/assets/330324/7006559/7588ad64-dc82-11e4-866b-57b31d8aca2f.png)

![mozillach2](https://cloud.githubusercontent.com/assets/330324/7006562/79b4c116-dc82-11e4-9d63-e4bc2a93f3c8.png)

**Comment by J0WI** [comment]
We can try to make the .promo-face tiles a bit transparent and setting a grayscale filter (if not hovered).
![transparent-grayscale](https://cloud.githubusercontent.com/assets/5710638/7006883/ed02f708-dc84-11e4-97fb-3576ee3afc2f.png)

**Comment by freaktechnik** [comment]
I'd suggest something along the lines of
![screen shot 2015-04-06 at 20 32 25](https://cloud.githubusercontent.com/assets/640949/7009669/2c1b82e0-dc9c-11e4-81e0-7078305ba0cb.png)

I don't think we'd need any additional content for the swiss apps tile.

**Comment by MichaelKohler** [comment]
1) I think making the faces grey would help a lot
2) to freaktechnik's suggestion: I'd like to have the site as "Swiss" as possible, therefore your suggestion seems perfect. We don't necessarily have to promote other Mozilla products. Just some nits:
- Having the Gear store on top seems weird to me, not sure if we want to place that high in the user's vision
- We probably can get rid of the "Contact" Tile since we have the mailing list further down

**Comment by freaktechnik** [comment]
> Having the Gear store on top seems weird to me, not sure if we want to place that high in the user's vision

It's just any random tile. The reason it's up there is to try and keep the small tiles to the edge (which helps with the overall appearance/busyness). But six one hight tiles in a row is maybe a bit much. It's just the best balance I could find.

> We probably can get rid of the "Contact" Tile since we have the mailing list further down

No problem, we can always replace it with a face.

**Comment by freaktechnik** [comment]
After some discussions with @MichaelKohler in IRC we've got two variants:
a) ![Variant A](https://i.imgur.com/6F2S6nF.png)
b) ![Variant B](https://i.imgur.com/Aa084tt.png)

I personaly prefer a, and https://www.evernote.com/shard/s41/sh/14f5b367-1181-4a87-9c1a-fec2ff7bd9f7/d1ea858e8207e9be6d8de6557a2f803f is my justification.

**Comment by MichaelKohler** [comment]
Just to be clear the "Firefox OS" is a 1x1 random tile, the "Choose independet" is a 2x1 random tile. The same for the Marketplace and Dev Edition for the second suggestion.

I'd like to go with A) as well after seeing @freaktechnik's explanation. 

Is there anything we would need to add that to make it a good website? I think all the important stuff for mozilla.ch is on there and we have two random tiles to promote other stuff.

**Comment by colinfrei** [comment]
I like B because the events are more prominent and the big blocks are split up a bit more. Overall both look good though :)

**Comment by MichaelKohler** [comment]
Do we have any other input here?

**Comment by MichaelKohler** [comment]
We still need some tile styling here.

**Comment by MichaelKohler** [comment]
IMHO just the "Apps made in Switzerland" Tile still needs styling. Otherwise it looks good to me.

**Comment by J0WI** [comment]
@MichaelKohler should i make a pull with https://github.com/mozillacommunitych/mozilla.ch/issues/30#issuecomment-90118925?

**Comment by MichaelKohler** [comment]
@J0WI since we have less tiles now, I think it's not absolutely necessary.
