### ISSUE TITLE
Links for mozilla domains 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozillacommunitych/mozilla.ch#31]
As the website is localized I was wondering if you don't want the mozilla domains to be linked to the localized version. Here I mean: 
- https://download.mozilla.org/
- https://www.mozilla.org/firefox/developer/
- https://www.mozilla.org/firefox/android/

**Comment by ioana-chiorean** [comment]
This is a Question type of Issue - it seems I can't set labels. :D

**Comment by ioana-chiorean** [comment]
I saw just after entering this that the website is available in 5 lang.. Not sure how to set the links to offer the localized version of each..

**Comment by MichaelKohler** [comment]
Thanks for the input. Those websites should localize themselve according to the browser language. I think this is enough. What do the other people think?

**Comment by freaktechnik** [comment]
I think it's fair to not link to the localized version of those sites, as, especially for english, visitors might understand other languages, which we don't offer, but mozilla has.

**Comment by MichaelKohler** [comment]
on the other side, if we have somebody visiting /rm for example, we should definitely link to the rm Download of Firefox for example. I mean, that's one thing we want to promote with the site, right? Otherwise people won't find out that easily that there is a localized build.

**Comment by J0WI** [comment]
If you would visit mozilla.org in a language, that is not set in your browser, you still get a hint to visit the translated version (e.g. https://www.mozilla.org/nl/). (Would be nice if we had something similar btw.)
Sadly rm is not a very common attribute in the Accept-Language header, even in Grisons.

**Comment by freaktechnik** [comment]
@J0WI: we have that from tabzilla. and it even works now (see c5dd86645638bcef7183d5e5453579ddb07babd6).

**Comment by J0WI** [comment]
@freaktechnik does not work for me, neither on localhost nor on mozilla-ch.colinfrei.com

**Comment by freaktechnik** [comment]
@J0WI 
![mozzch-languageswitch](https://cloud.githubusercontent.com/assets/640949/7005226/800dce10-dc76-11e4-9e22-983993893be4.png)

I think it only shows for language that you haven't listed in your content languages (-> I don't get it on de and en). And if you press no once on a domain it's gone forever.

**Comment by J0WI** [comment]
@freaktechnik Not shown on http://mozilla-ch.colinfrei.com/fr using a new profile. Still working on https://www.mozilla.org/fr/.

**Comment by freaktechnik** [comment]
So we discovered in IRC, that this is due to our alternate links having the -CH region specification, and tabzilla doesn't suggest de-CH  to people who'd like to see de content. Or en-CH to people who'd like en content.

**Comment by MichaelKohler** [comment]
This is fixed now.
