### ISSUE TITLE
Use Affiliates? 

### ISSUE THREAD

**Issue by ioana-chiorean** [mozillacommunitych/mozilla.ch#32]
I am not sure If you know or considered to use some affiliate links:
- https://affiliates.mozilla.org/en-US/

This is a Question type of Issue - it seems I can't set labels. :D

**Comment by freaktechnik** [comment]
I don't see any reason why we would - unless mozilla would prefer that for tracking reasons. Though for example mozilla.de doesn't seem to use affiliates links either.

**Comment by MichaelKohler** [comment]
I don't think we need to do that. At least not from our side. If Mozilla wants it, sure, but not otherwise. Therefore okay right now.
