### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#34]
- [ ] meta description
- [x] alternate favicons (svg, png "apple-touch-icon" etc.)
- [ ] improve page speed (=> #33)
- [x] title
- [ ] open graph
- [x] https
- [ ] microdata
- [ ] server warm-up

**Comment by MichaelKohler** [comment]
Title, Page Speed and maybe favicons: yes
Meta keyword: not really I think

**Comment by J0WI** [comment]
Oh and we should not forget to request https in #17

**Comment by MichaelKohler** [comment]
Asked in the bug. Thanks for the info.

**Comment by freaktechnik** [comment]
For page-speed we should probably consider sending a Last-Modified based on the last update to the reps event calendar (and eventually twitter). Not sure if this data is easily available, though. We currently tell the client not to cache the site.

**Comment by MichaelKohler** [comment]
I just did a quick search on Google:

"mozilla switzerland": no mention on the first page
"mozilla schweiz": first result
"mozilla suisse": mozilla-ch.colinfrei.com/fr is in there, but not mozilla.ch -> we definitely need to fix this!
"mozilla svizzera": 8th place
"mozilla svizra": 2nd place, though "grrd's 4 in a Row - mozilla.ch" might not be a perfect title ;)

We should look into that :( Any volunteers?

**Comment by J0WI** [comment]
I got mozilla.ch as the first result on DDG with region enabled, except for the Italian ones.
@colinfrei should serve a `X-Robots-Tag: noindex` header.

**Comment by J0WI** [comment]
Thoughts about open graph?
AKAIK it's not yet an official standard.

**Comment by MichaelKohler** [comment]
As long as it helps us, sure, why not :)

**Comment by J0WI** [comment]
Added Site title in d33e58a.
I think mozilla.org is a good hint for what is needed for open graph.

@MichaelKohler would you like to write a short description of Mozilla Switzerland?

**Comment by MichaelKohler** [comment]
Mozilla Switzerland is a volunteer run organization engaged in promoting openness, innovation, and opportunity on the Web in the country. Mozilla Switzerland is part of the global community of Mozilla Foundation.

**Comment by J0WI** [comment]
Thanks!
Ping @teoli2003 @Mte90 @gion-andri for help to translate.

**Comment by freaktechnik** [comment]
What kind of microdata are you thinking of? We should already have 'organization' micro data embedded into the page around the footer area.

**Comment by Mte90** [comment]
Mozilla Switzerland é una organizzazione di volontari che si occupa di promuovere apertura, innovazione e opportunitá nel Web nel suo paese. Mozilla Switzerland é parte di una community globale della Mozilla Foundation. 

Italian is here :-)

**Comment by gion-andri** [comment]
Romansh:

Mozilla Svizra è ina organisaziun manada da voluntaris ed engaschada per promover l’avertadad, l’innovaziun ed las pussaivladads en il web per noss pajais. Mozilla Svizra fa part da la communitad globala da la Mozilla Foundation.

**Comment by J0WI** [comment]
Enabled caching and compression in https://github.com/mozillach/mozilla.ch-docker/commit/79c1a51874a5b747ff930a8817ee8b3217ee70d6.
But our slowest part is still the Twitter iframe.
@freaktechnik Could we also load our JS resources asynchronous by adding the async attribute?

**Comment by freaktechnik** [comment]
I'd have to look into what we can load when (be it defer or async). However I'll do that work for the js deps branch where there is no more tabzilla to worry about.

**Comment by J0WI** [comment]
> What kind of microdata are you thinking of? We should already have 'organization' micro data embedded into the page around the footer area.

Microdata would be also interesting for the events tile

**Comment by MichaelKohler** [comment]
Given the current ranking, I'm closing this one. Please open specific issues if we need to do anything else.
