### ISSUE TITLE
Check Localizations

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#35]
We probably should check FR, IT, RM again to make sure we didn't add new strings. In IT there are some translations missing.
- [x] FR
- [x] IT
- [x] RM

**Comment by MichaelKohler** [comment]
I have asked Jean-Yves Perrier and Daniele Scasciafratte to review the FR/IT translations.

@gion-andri could you please do it for RM? :)

**Comment by MichaelKohler** [comment]
FR is checked and updated.

**Comment by freaktechnik** [comment]
IT :white_check_mark:

**Comment by gion-andri** [comment]
RM :white_check_mark: (in 5ec093069e70a21272314ee12d5d497a0e173862)
