### ISSUE TITLE
Puzzle is listed twice

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#41]
Gerard's puzzle app is listed twice. We could also link to his new app: https://marketplace.firefox.com/app/grrds-dice

Also the dialog probably needs some more styling, not much though.

**Comment by freaktechnik** [comment]
he has his 4 in a row listed twice in the marketplace - once as webapp and once as packaged app.

**Comment by freaktechnik** [comment]
Closing this here, please create a new bug for the styling, as that's a different issue.
