### ISSUE TITLE
"[...] the dialog probably needs some more styling, not much though."

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#42]
No idea what @MichaelKohler has in mind, but I closed his issue, since he kind of made an unclear issue, so I've opened a new one for the second part now. (For reference: initiation of this issue was #41)

**Comment by J0WI** [comment]
Note that the `<dialog>` element is not officially supported yet: https://bugzilla.mozilla.org/show_bug.cgi?id=840640

**Comment by freaktechnik** [comment]
@J0WI That's why there is css and other elements shimming some of its functionality.
