### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#43]
We need a docker container for the hosting at community IT, see #17

**Comment by MichaelKohler** [comment]
This docker container will run on mesosphere.com

**Comment by freaktechnik** [comment]
I've created a [new repo](https://github.com/mozillach/mozilla.ch-docker) for the container build files (Dockerfile and attachments), since we'd always want to build the docker image from a clean clone of this repo and not the local (dirty) copy of it.

Note that it can be used with your local version of the mozilla.ch repo by replacing the git clone instruction by `COPY ../path/to/the/mozilla.ch/repo /var/www/html`.
