### ISSUE TITLE
Firefox for Android logo

### ISSUE THREAD

**Issue by elioqoshi** [mozillacommunitych/mozilla.ch#45]
The Firefox for Android logo [1] is outdated and it uses the old 2009-2012 Firefox Logo. It should be updated with the [2] image mozilla.org currently uses.

[1]
![ff old](https://cloud.githubusercontent.com/assets/5436686/9904385/a22158be-5c7d-11e5-8165-5b7d9d19ff7e.jpg)

[2]
![fennec](https://cloud.githubusercontent.com/assets/5436686/9904386/a2235f42-5c7d-11e5-8efc-5ffc1cb45b52.jpg)

Further, the Firefox for Android "widget' disappears for me when viewing the website on a mobile

**Comment by freaktechnik** [comment]
Yes, the "promo" widgets are hidden when we have little horizontal space, to save vertical space. There are other widgets disappearing depending on the width, too.

**Comment by elioqoshi** [comment]
Makes sense!

**Comment by freaktechnik** [comment]
Should we use the jpg version you uploaded, or is there a better source (svg, just the dude)?

**Comment by elioqoshi** [comment]
Try to get it from the mozilla.org website, that should suffice

**Comment by freaktechnik** [comment]
The version I get there is pretty small, compared to what you have in the jpg. I'd guess that's a retina version?

**Comment by elioqoshi** [comment]
I just zoomed in and made a screenshot, soo :)
