### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#48]
We haven't a favicon yet.
The Mozilla [m] might be problematic.

Any suggestions?

I would like to support the [SVG favicon](https://bugzilla.mozilla.org/show_bug.cgi?id=366324) feature.

**Comment by freaktechnik** [comment]
See also issue mozillach/mozillach_branding#1. Further that's just the same favicon as mozilla.org for now.

**Comment by MichaelKohler** [comment]
Who wants to move this forward?

**Comment by ghost** [comment]
If only github supported SVG attachments. (_sigh!_)
It won't even let me attach it compressed as a ZIP.

How about <a href="http://marco.dilbert.ch/mozilla.ch_favicon.svg">this one</a>? It looks okay, even at <a href="http://marco.dilbert.ch/mozilla.ch_favicon_test.htm">16x16px</a>.
Any suggestions? Ideas?

**Comment by MichaelKohler** [comment]
This is a great idea, I like it. But I guess we'd want to use the "m" from the logo?

**Comment by ghost** [comment]
Are you referring to the large "m" from "mozilla.ch"?
16x16px won't leave us too much room for variations,
but I'm generally open for any kind of suggestions.

Legibility and recognition might be the most important
factors here. Is the title font from mozilla.ch safe to use?
I don't want to attract the wrath of some design copyright
holder.

Do you have any preferences regarding the colors?
I think the background should match the red banner
on top. And personally, I prefer the cross to be white.
So any contrasting color for the "m" might do nicely.

**Comment by MichaelKohler** [comment]
Yes, the "m" from http://mozilla.ch/images/mozillach_wordmark-white.svg . I think it's okay to extract it from there, as long as we're using it for the purpose of mozilla.ch.

Regarding the color, in theory it's okay to use any color. I agree with the red of the banner and the white of the cross. Could you upload one with the "m" being #FF9500? I'd go with one of those colors listed here: https://www.mozilla.org/en-US/styleguide/identity/firefox/color/

**Comment by J0WI** [comment]
Or we use one of the colors from the bottom of mozilla.ch?

**Comment by MichaelKohler** [comment]
mh, those are dynamic, we would need to pick one that is on the page all the time and then make sure we don't remove it.

The goal here is to also use this as a Twitter Avatar as far as I know. This might need to be taken into consideration as well I guess.

**Comment by J0WI** [comment]
Sure. In this case «Mozilla» should be more prominent than «Switzerland».

**Comment by ghost** [comment]
Ok, I've updated the <a href="http://marco.dilbert.ch/mozilla.ch_favicon_test.htm">samples and icons</a>. The new "m" is more recognizable.
I think yellow looks better than light orange, though. The contrast was better.
Where do you think the cross should go? Left? Right? Or somewhere else?

**Comment by MichaelKohler** [comment]
I agree, the yellow looks better. Great work so far!

Here are my suggestions:

http://codepen.io/anon/pen/xZxJJX

http://codepen.io/anon/pen/PZoBBL

**Comment by ghost** [comment]
Yay! The cross on the right seems more natural. And the white "m" looks good, too. :+1:
I've made <a href="http://marco.dilbert.ch/mozilla.ch_favicon_test.htm">another few slight adjustments</a>. Some thoughts for a final design:
- The 16x16px favicon will almost certainly need some manual overhaul.
- For larger representations we may need to tune the "m" (ours is heavily simplified).
- We may still want to experiment with other light color variations for the "m".

**Comment by freaktechnik** [comment]
This looks really nice and I'd say the 16px variant untweaked is passable, but I guess we can get more out of it.

**Comment by ghost** [comment]
Ok, here comes <a href="http://marco.dilbert.ch/mozilla.ch_favicon_test.htm">another update</a>. This time please focus on the different colors. I had to ditch the pixel-alignment idea, though. Whenever it looked great in 16x16, the bigger sizes sucked (and vice versa).

**Comment by freaktechnik** [comment]
The violet doesn't have enough contrast and the green looks weird (probably because of the red-green combination).

**Comment by ghost** [comment]
Let's drop violet (there may be hope for green, though). I've prepared <a href="http://marco.dilbert.ch/mozilla.ch_favicon_test.htm">another update</a> with fewer colors.
Any favorites?

The 16x16px problem is solved, too. Clear your browser cache and check the favicon of the link above.

We may want to design larger logos (Twitter Avatar?) in a separate ticket. A one-size-fits-all solution doesn't make much sense here. The original tiny favicon is just too special a use-case. But we have a good base to build upon.

**Comment by freaktechnik** [comment]
I'd say those larger version belong to the branding ticket (mozillach/mozillach_branding#1). In terms of colors I feel like all of them are acceptable, but they are for sure not equal on what the logo says.

**Comment by MichaelKohler** [comment]
I'd vote for the yellow one. Other thoughts?

**Comment by J0WI** [comment]
yellow is to similar to Post for me, I like the white one.

Note that the colors will look very different in context of a (dark/light theme) tab. So I recommend to use simple items and good contrasts.
e.g. the Swiss cross is not really visible on my display here.

**Comment by MichaelKohler** [comment]
Any objections to go with http://marco.dilbert.ch/favicon_white.svg in that case?

**Comment by freaktechnik** [comment]
I'm totally fine with that.
@DocZweirad do you want to make minor adjustments to it for mozillach/mozillach_branding#1 so we can also use it as an avatar all over the place or do you think it's fine like this.

**Comment by ghost** [comment]
@freaktechnik:
Actually, it's the other way round (already ok for the avatar). ;-)

It's the favicon version that still needs some minor tweaking.
In order to make the used symbols easier to recognize, I'd go
for something like this: http://marco.dilbert.ch/favicon_dev.svg.
(The grid is actually just for demonstrating the pixel alignment.)

**Comment by MichaelKohler** [comment]
That is better recognizeable. Do we want to go ahead with that?

**Comment by freaktechnik** [comment]
Should be fixed with #64 and 6c7d720ae9b26ed1a931450cb1c0efe645bef908.
