### ISSUE TITLE
BÜPF/NDG Tile

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#50]
Instead of the Hello one for now. Links to a modal dialog with more information and further links.

**Comment by freaktechnik** [comment]
I can help with the setup of the "modal" popup.

**Comment by J0WI** [comment]
Created WIP branch.
We need an image/symbol for the NDG tile (camera?, eye?, NSA?)

**Comment by MichaelKohler** [comment]
I'd go for the camera or the eye

**Comment by J0WI** [comment]
Okay, the Unicode chars for camera are horrible:
🎥📹📸📷
The eye (👁) doesn't look good in the Mozilla font.

I'll look for an SVG.

**Comment by J0WI** [comment]
https://upload.wikimedia.org/wikipedia/commons/7/72/Cctv.svg
https://openclipart.org/download/167030/cctv-simbolo.svg
https://openclipart.org/download/161083/cctv.svg
https://openclipart.org/download/189232/1385784407.svg

all of them are CC0

**Comment by MichaelKohler** [comment]
I like the first one best, the question now is if we should do a yellow tile.. mmh.

**Comment by J0WI** [comment]
We can modify the image and extract the camera. I used the color from https://www.nachrichtendienstgesetz.ch/, but this is irrelevant since there are multiple platforms.
(=> Which platform should we support?)

**Comment by MichaelKohler** [comment]
let's go with nachrichtendienstgesetz.ch and http://stopbuepf.ch/ for now

**Comment by J0WI** [comment]
Where can I find the improved SVGs from Mozilla Day?

**Comment by MichaelKohler** [comment]
sent out a mail to Marco to ask if he can upload it somewhere

**Comment by MichaelKohler** [comment]
Voila, https://owncloud.michaelkohler.info/index.php/s/XjDAmcsRem2I4bW

Please note that we won't be able to use the mozilla wordmark ones, since those are not based on the branding font, but Fira Sans.

**Comment by J0WI** [comment]
"Überwachungsstaat" is to long for a portrait

**Comment by freaktechnik** [comment]
`Üb<wbr>er<wbr>wach<wbr>ungs<wbr>staat`

**Comment by J0WI** [comment]
`hyphens: auto` or at least `&shy;`
But these are ugly solutions

**Comment by freaktechnik** [comment]
Uh, yeah, I mean `&shy;`.

**Comment by ghost** [comment]
Beware of [Mister Duden](http://www.duden.de/rechtschreibung/Ueberwachungsstaat). He begs to differ on the hyphenation:
- Über|wa|chungs|staat

So we would most likely want to use something along the lines of
- <code>&amp;Uuml;ber&amp;shy;wa&amp;shy;chungs&amp;shy;staat</code>

**Comment by J0WI** [comment]
ToDo:
- [x] Translation (needhelp @gion-andri)
- [x] Dialog Box (needhelp @freaktechnik)
- [ ] consider new tile color, because it looks weird in combination with the green tiles from Mozilla

**Comment by freaktechnik** [comment]
Re dialog box:
It needs markup similar to https://github.com/mozillach/mozilla.ch/blob/master/app/Resources/views/index.html.twig#L214-L244. Make sure to change the ID of the overlay. Not sure if there are any styles specific to that id - if there are we should probably consider making an "overlay" class.
It seems like we'd also want to generalize the close button.

Setting it up is as easy as adding a JS file similar to https://github.com/mozillach/mozilla.ch/blob/master/app/Resources/public/scripts/ch-apps.js#L1-L11 with adjusted elements for the overlay root and the click listener for the tile.

**Comment by J0WI** [comment]
@freaktechnik I tried to use the same dialog box for ndg and ch-apps, but won't work for me. Now I have everything twice, would be great if you could help merging them.

@MichaelKohler referring to our meetup you will provide a text for the box :)

**Comment by freaktechnik** [comment]
@J0WI there is no reason to merge them, all we could do is to have two containers that are hidden depending on what we need, but I'm not sure that saves much.

**Comment by J0WI** [comment]
_poke_ @MichaelKohler

**Comment by MichaelKohler** [comment]
I know, I know.. here are the German and English texts, sorry for the delay.

**DE:**
_Die Sicherheit und der Schutz der Daten einer Person im Internet sind von grundlegender Bedeutung und dürfen nicht als optional betrachtet werden._
- Mozilla Manifesto (https://www.mozilla.org/de/about/manifesto/)

Mozilla steht für die Privatsphäre aller Internet-Benutzer ein. Dies ist tief in unserem Manifesto verankert. Nach diversen Privatsphäre-Initiativen in den USA, Indien, Frankreich und Deutschland, gilt es nun das Referendum gegen die Nachrichtendienst-Gesetz-Reform zu unterstützen. Die Schweizer Mozilla-Community bittet daher alle Internetbenutzer sich über die geplante Reform zu informieren und den Referendumsbogen zu unterschreiben. Weitere Informationen sowie den Referendungsbogen findest du auf den untenstehenden Webseiten.

<Links to the websites>

**EN:**
_Individuals’ security and privacy on the Internet are fundamental and must not be treated as optional._
- Mozilla Manifesto (https://www.mozilla.org/en-US/about/manifesto/)

Mozilla cares about the privacy of all internet users. This is based on our manifesto. After multiple privacy initiatives in the US, India, France and Germany, it's time to support the referendum against the planned intelligence service law reform. The Swiss Mozilla community therefore asks every internet user to inform yourself about the reform and sign the referendum sheet. You can find more information and the signature form on the websites below (unfortunately the information is only available in German and French).

**FR:** (translation note: we are using the "formal" version of "you" and in singular)
_La sécurité des personnes sur Internet est fondamentale et ne doit pas être facultative._
    - Le Manifeste Mozilla (https://www.mozilla.org/fr/about/manifesto/)

... Rest to be translated ...

**IT:** (translation note: we are using the "formal" version of "you" and in singular)
_La sicurezza e la privacy di ogni persona su Internet sono prerogative fondamentali e non devono essere considerate facoltative._
    - Il manifesto di Mozilla (https://www.mozilla.org/it/about/manifesto/)

... Rest to be translated ...

**RM:** (translation note: we are using the "formal" version of "you" and in singular)

... to be translated ...

For FR and IT we hopefully get the text shortly, and maybe @gion-andri wants to translate for RM?

**Comment by MichaelKohler** [comment]
Change in plans: let's go for http://nachrichtendienstgesetz.ch/ and http://ndg-referendum.ch/ .. not büpf, we can do that later..

**Comment by Mte90** [comment]
In Italian:

Mozilla tutela la privacy di ogni persona su internet. Questo é definito nel nostro manifesto. Dopo molte iniziative sulla privacy in USA, India, Francia e Germania, ora é il momento di sostenere il referendum contro una riforma della legge sullo spionaggio. La community Svizzera di Mozilla chiede ad ogni utente di internet di informarsi sulla riforma e firmare il referendum. 
Puoi trovare maggiori informazioni ed il modulo per partecipare sul sito sottostante (sfortunatamente le informazioni sono in Tedesco e Francese).

**Comment by J0WI** [comment]
Thanks! I just updated the text.
I'll add some CSS soon.

Maybe @teoli2003 could translate to FR?

**Comment by J0WI** [comment]
who likes to review?

**Comment by MichaelKohler** [comment]
Why is one URL translated and one is not? there is a FR link as well for the second one. Code looks good to me otherwise. Visual review coming up in a few minutes

**Comment by MichaelKohler** [comment]
Great work so far!
- can we move the "Nein zum Überwachungstaat" text a little bit up to create more space between the text and the camera?
- maybe we could have the same margin as the blockquote for text as well?
- The links are not prominent enough.. could we make bigger boxes and display them inline and centered?

![screen shot 2015-11-27 at 01 34 17](https://cloud.githubusercontent.com/assets/330324/11432120/6afe349e-94a7-11e5-96d1-1d2ce97fb76f.png)
![screen shot 2015-11-27 at 01 36 48](https://cloud.githubusercontent.com/assets/330324/11432121/6b18c322-94a7-11e5-8cbf-62e3d028d80b.png)

**Comment by J0WI** [comment]
Implemented all your feedback.
Links are now styled as boxes similar to the 'sign now' box on nachrichtendienstgesetz.ch

**Comment by J0WI** [comment]
I just opened PR #51 to discuss the review stuff

**Comment by teoli2003** [comment]
Something to translate in fr? The string + url looks ok in PR 51 (but I may have missed some text)

**Comment by MichaelKohler** [comment]
@teoli2003 that would be https://github.com/mozillach/mozilla.ch/blob/NDG/app/Resources/translations/messages.fr.yml#L56 and https://github.com/mozillach/mozilla.ch/blob/NDG/app/Resources/translations/messages.fr.yml#L58 .. (that is the "NDG" branch, not the master branch) .. would be great if you could do that! :)

**Comment by freaktechnik** [comment]
#51 is merged to master. Are all translations in?

**Comment by MichaelKohler** [comment]
Apart from RM I'd say so.. I will need a tutorial on how to deploy to the server as well ;)

**Comment by J0WI** [comment]
@MichaelKohler just do `git pull`
or rebuild your docker image

**Comment by freaktechnik** [comment]
there are no new dependencies so there should be no real "deployment" in the form of reinstalling deps needed, right? But you might be able to use this deployment thing that's already built in in the template from @colinfrei

**Comment by MichaelKohler** [comment]
I deployed and verified the source code. It is the new version. Then I cleared the cache (both with `rm -r app/cache/*`and via the `console` utility). Verifying that step proves that the cache folder is now empty. Nevertheless the cache gets rebuilt with an old version. Is there any other cache or what am I doing wrong? @colinfrei can you help here?

**Comment by MichaelKohler** [comment]
it's deployed now. Great work everybody!
