### ISSUE TITLE
mozorg.cdn.mozilla.net deprectaed?

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#54]
Die Ressourcen von mozorg.cdn.mozilla.net laden bei mir nicht mehr (403).
Müssen wir mozorg.cdn.mozilla.net mit mozilla.org ersetzten?

@MichaelKohler @freaktechnik?

**Comment by freaktechnik** [comment]
It seems tabzilla is now to be loaded as dependency of the project: https://github.com/mozilla/tabzilla/
EDIT: I assume resources were move to mozilla.org for http/2 optimization.

**Comment by freaktechnik** [comment]
Okay, I've checked every resource from mozorg.cdn.mozilla.net and they all still exist on www.mozilla.org. We might still want to think about using our own jquery and tabzilla, maybe even our own OpenSans. I've pushed 3865a84 that replaces all occurrences.

**Comment by MichaelKohler** [comment]
the CDN is back again, but I deployed freaktechnik's change as well

**Comment by J0WI** [comment]
Is there any statement from Mozilla which services are deprecated and what the best practise is?

**Comment by MichaelKohler** [comment]
Didn't see anything, but as long as we can use mozilla.org the same way, we should be fine. Might also just have been a problem on the CDN. Let's leave it like that and once we move to Community Ops servers we might need to reevaluate anyway.
