### ISSUE TITLE
Outsource JS dependencies

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#56]
We currently use a few JS libraries. Some of them are directly included within the repo, and some we use from Mozilla. We should think about loading them via composer.

We could load the following libraries via bower
- desandro/masonry
- freaktechnik/minimal-overlay
- mozilla-tabzilla

I'm not sure we'd still need jQuery with those. If only our scripts use it, we could also look into components/jquery from the composer components.

What we'd have to look into is where those would be installed into, so they aren't picked up by git but assetic still picks them up, or if we want to exclude them from assetic.
## TODO
- [x] Figure out how to replace the "language detection"

**Comment by MichaelKohler** [comment]
Makes totally sense. Let's go for it!

If we still need jquery, we should use from either mozilla.org or the CDN to make sure that it's cross-cacheable, so we don't need to serve it when users already visited mozilla.org.

Maybe @colinfrei can give a hint regarding the technical implementation (assetic and everything else)?

**Comment by colinfrei** [comment]
bower is js, composer is php. that said, there are a bunch of composet packages that allow including js libraries, though I'm not sure that's the way to go.

Maybe just have the bower install script be part of the deployment, and make it install to the web folder?

**Comment by freaktechnik** [comment]
I think https://packagist.org/packages/sp/bower-bundle is not too far off. It would allow us easy use of bower, since it claims to handle all the install steps via composer, which we already properly support with both the docker container and the other deployment method. I think this would also avoid having to temporarily install node etc. in the docker container just to load the bower packages.

**Comment by MichaelKohler** [comment]
@freaktechnik do you still want to pursue this?

**Comment by freaktechnik** [comment]
Sure, I'll have to look into what's the best solution given our deps and how to handle it with our current docker container build steps, but it should be doable ;)

**Comment by freaktechnik** [comment]
Moving away from the old tabzilla to the new one (which is just a link with defined styling) breaks how our l10n detection system currently works (the little "do you want to change your language" thing on the top). @colinfrei could we replace that with server-side language detection in the router?

**Comment by freaktechnik** [comment]
If we want to get rid of jQuery someone would have to rewrite the mobile menu code, btw.

**Comment by freaktechnik** [comment]
See the [js-deps branch](https://github.com/mozillach/mozilla.ch/tree/js-deps) for the current WIP.

**Comment by freaktechnik** [comment]
I guess we should use something like http://symfony.com/doc/current/cmf/book/handling_multilang.html?
