### ISSUE TITLE
Get Smart On the Web

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#57]
There is an interesting campaign we should take part of on mozilla.ch.

The old campaign for private browsing seems to be obsolete, I updated the url in https://github.com/mozillach/mozilla.ch/commit/b298d185762c7bce1bf6371c32c75d313092159e

https://www.mozilla.org/teach/smarton/surveillance/
Fits perfectly to NDG/BÜPF

https://www.mozilla.org/teach/smarton/tracking/
Fits to Tracking Protection

https://www.mozilla.org/teach/smarton/security/
Fits to password manager? Let's Encrypt?

**Comment by MichaelKohler** [comment]
Sounds good to me, do we want to create a tile for it?

**Comment by J0WI** [comment]
Do we want 3 random tiles for each or just one meta tile?

**Comment by MichaelKohler** [comment]
One meta tile should be enough

**Comment by MichaelKohler** [comment]
I did this as part of #61 . Pretty nice and definitely needed for our website, great idea!

Let's continue the discussion there.
