### ISSUE TITLE
Finish Docker image so we can deploy it through Community IT

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#60]
We need to get our Docker image finished so we can give it to Community IT to deploy it.

@freaktechnik what's the current status here?

**Comment by freaktechnik** [comment]
It works, I've set it up on the box you provided me earlier. I also expanded the readme of the docker repo with more specific explanations.

**Comment by MichaelKohler** [comment]
Great, this is running on http://46.101.156.191/de then .. I will let the DNS point to that IP then for now so I can remove my server. Is that okay?

Great work!

**Comment by freaktechnik** [comment]
That sounds like a good plan. I'd still like an answer to the API key question, since that effectively blocks proper deployment on mesos. We will also have to figure out "deployment" will work for us.

**Comment by MichaelKohler** [comment]
Perfect, let's close this one then :)
