### ISSUE TITLE
Clean up our tiles

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#61]
I would suggest the following (also due to recent announcements):

Add:
- SmartOn tile (as proposed by @J0WI in #57)
- There is a new MDN-Tile on mozilla.org, do we want to add this as well?

Delete:
- Firefox Marketplace
- Firefox OS
- Firefox OS Apps in Switzerland (maybe replace it with Firefox Add-ons that are from Switzerland?)
- Independent (I'm sure we have other good tile ideas for now to convey that message)

TODO:
- Update text for the NDG tile

**Comment by freaktechnik** [comment]
Whatvwill take the place of the CH Apps tile? It's quite a lot of space.

**Comment by J0WI** [comment]
- Update text for the NDG tile

**Comment by MichaelKohler** [comment]
I think if we reorder a few of them, we can better distribute the space and have some bigger tiles for more important ones. I don't think we need another big one like that.

**Comment by J0WI** [comment]
s/Apps/Add-ons/ ?

**Comment by MichaelKohler** [comment]
@J0WI do you mean Firefox Add-ons? The OS ones have about the same state as apps for now.

**Comment by J0WI** [comment]
Yes, I meant Firefox/Thunderbird Add-ons.
We should prefer the new web extensions here.

**Comment by MichaelKohler** [comment]
That would be one possibility. I've added this as question to the top comment.

**Comment by MichaelKohler** [comment]
I have updated the tiles, it now has only up-to-date tiles and 2 new ones. This is all in the "update_tiles" branch for now, until I got feedback on this. Any improvement ideas? Other feedback?

![screen shot 2016-02-25 at 21 55 48](https://cloud.githubusercontent.com/assets/330324/13334198/20f21a54-dc0b-11e5-91a8-a1d3871833b6.png)

I have also updated the NDG text in EN and DE, this will need updates in the locales as well. @teoli2003 @Mte90 and @gion-andri would you be so kind and update your locales for https://github.com/mozillach/mozilla.ch/blob/tiles_update/app/Resources/translations/messages.en.yml#L52 in that branch? Thanks already! :)

I know that we would be losing some Swiss context with that, but I have an idea on how we can solve this, but I will create a new issue for that.

**Comment by teoli2003** [comment]
I will, though I'm traveling and therefore I can't before Monday :-(

I've added an action item to my todo list though.

On 25/02/2016 22:02, Michael Kohler wrote:

> I have updated the tiles, it now has only up-to-date tiles and 2 new 
> ones. This is all in the "update_tiles" branch for now, until I got 
> feedback on this. Any improvement ideas? Other feedback?
> 
> screen shot 2016-02-25 at 21 55 48 
> https://cloud.githubusercontent.com/assets/330324/13334198/20f21a54-dc0b-11e5-91a8-a1d3871833b6.png
> 
> I have also updated the NDG text in EN and DE, this will need updates 
> in the locales as well. @teoli2003 https://github.com/teoli2003 
> @Mte90 https://github.com/Mte90 and @gion-andri 
> https://github.com/gion-andri would you be so kind and update your 
> locales for 
> https://github.com/mozillach/mozilla.ch/blob/tiles_update/app/Resources/translations/messages.en.yml#L52 
> in that branch? Thanks already! :)
> 
> I know that we would be losing some Swiss context with that, but I 
> have an idea on how we can solve this, but I will create a new issue 
> for that.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/mozillach/mozilla.ch/issues/61#issuecomment-188986325.

## 

"Prenez soin des minutes, les heures prendront soin d'elles-mêmes."
P.D. Stanhope (4e baron de Chesterfield, 1694-1773)

**Comment by MichaelKohler** [comment]
Any update on this? Or could this be merged once translated?

@teoli2003 @Mte90 @gion-andri quick ping for translation here. Would be great if you could support us here :)

**Comment by Mte90** [comment]
I look on that asap!

**Comment by MichaelKohler** [comment]
Maybe @gperriard could help out with the French translation here? The goal is to have the new English string here https://github.com/mozillach/mozilla.ch/blob/tiles_update/app/Resources/translations/messages.en.yml#L52 translated to FR in https://github.com/mozillach/mozilla.ch/blob/tiles_update/app/Resources/translations/messages.fr.yml#L53 (please notice the different branch name, this is not master yet).

Also, do we want to block on the rm translation, or could we go once FR and IT is completely done?

**Comment by gion-andri** [comment]
In my opinion, you don't have to block on the rm translation in such cases.

**Comment by teoli2003** [comment]
Hi!

I may look at the wrong place, but messages.en.yml#L52 is already 
translated in messages.fr.yml#L53…

## 

Jean-Yves Perrier
Senior St. Project Manager, Developer Documentation / MDN

**Comment by MichaelKohler** [comment]
> I may look at the wrong place, but messages.en.yml#L52 is already translated in messages.fr.yml#L53…

Sorry, I was not specific enough. The initial string was translated, but I have updated it and need a retranslation of it.

**Comment by teoli2003** [comment]
Ha!

PR in. Sorry for being blind.

## 

Jean-Yves Perrier
Senior St. Project Manager, Developer Documentation / MDN

**Comment by MichaelKohler** [comment]
Thanks everyone, the IT translations need another update, but we will create a second issue for this, so we can close this. Merged to master.
