### ISSUE TITLE
Update ndg.desc for italian

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#68]
The description string was changed to add more specific information that it will b ehappening in september. The italian translation isn't updated yet. See https://github.com/mozillach/mozilla.ch/blob/master/app/Resources/translations/messages.en.yml#L53

Can you help there @Mte90 ? Thanks!

**Comment by Mte90** [comment]
Done https://github.com/mozillach/mozilla.ch/pull/74
