### ISSUE TITLE
replace NDG with BÜPF during the referendum

### ISSUE THREAD

**Issue by J0WI** [mozillacommunitych/mozilla.ch#76]
We need to update the text a bit a change the links to the BÜPF site(s).

Links will be https://www.buepf.ch/ and https://www.lscpt.ch/

**Comment by MichaelKohler** [comment]
@J0WI can you do that? English and German would be good to have at first. Then we can ask Geoffroy or Jean-Yves for French.

**Comment by J0WI** [comment]
@MichaelKohler I'm quite busy at the moment. Could you provide a short text? I can implement it then.

**Comment by MichaelKohler** [comment]
Thanks for driving this, I will provide the text during the weekend.

**Comment by J0WI** [comment]
_ping_ @MichaelKohler

**Comment by MichaelKohler** [comment]
sorry about that, busy me ;)

Deutsch:

Mozilla steht für die Privatsphäre aller Internet-Benutzer ein. Dies ist tief in unserem Manifesto verankert. Nach diversen Privatsphäre-Initiativen in anderen Ländern und unseren Initiativen betreffend des NDG-Referendums, welches im September zur Abstimmung kommt, gibt es Weiteres für uns zu tun.

Bis am 7. Juni läuft die Frist für das Referendum gegen die BÜPF-Revision, welche die Privatsphäre jedes Internet-Benutzers gefährdet. Die Schweizer Mozilla-Community bittet daher alle Internetbenutzer sich über dieses auf unterstehenden Webseiten zu informieren und das Referendum zu unterschreiben.

English:

Mozilla cares about the privacy of all internet users. This is based on our manifesto. After multiple privacy initiatives in other countries and our efforts for the NDG-Referendum which is being voted on by the public in September, there is more for us to do.

The Referendum for the BÜPF law revision has started and is ongoing until July 7th. The revision threatens the privacy of all internet users. The Swiss Mozilla community therefore asks every internet user to inform yourself about this referendum on the websites below and sign the referendum.

@gperriard or @teoli2003 could you please translate this to FR and post it here?
@Mte90 could you do the same for IT?

Thanks a lot!

**Comment by J0WI** [comment]
Feel free to replace `surveillance-laws` with a better name.
I didn't remove the ndg strings, because we may reuse them during the votes.

**Comment by Mte90** [comment]
Italian:
Mozilla tiene alla privacy di tutti gli utenti su internet. Tutto questo é scritto nel nostro manifesto. Dopo molte iniziative in diversi paesi e la nostra campagna per il NDG-Referendum, che é stato votato in settembre, abbiamo ancora molto da fare.
Il Referendum per la revisione della legge BÜPF é iniziato e finità il 7 luglio. La revisione tratta la privacy di tutti gli utenti su internet.La community svizzera Mozilla chiede a tutti gli utenti di internet di informarsi riguardo questo referendum sui siti sottostanti e di partecipare al referendum.

**Comment by gperriard** [comment]
@MichaelKohler here is the french version:
Mozilla défend la vie privé des utilisateurs d'Internet. Ceci est inscrit dans notre manifeste. Après de multiple initiatives dans différents pays et notre campagne en faveur du référendum concernant la NGD (loi sur le renseignement) qui va été voté septembre, nous sommes à nouveau sollicités.

Le référendum sur la LSCPT (loi sur la surveillance de la correspondance par poste et télécommunication) a commencé et se termine le 7 juillet. La révision de la loi sur la surveillance menace la vie privé des utilisateurs d'Internet.
La communauté Mozilla en Suisse demande à tous de s'informer sur ce référendum en allant sur le site Internet ci-dessous et de signer celui-ci.

**Comment by MichaelKohler** [comment]
Thanks Geoffrey!

@J0WI I think we have all necessary strings translated now

**Comment by J0WI** [comment]
@MichaelKohler I think Romansh is not really a blocker, so we should push this to live urgently (not much time left to sign).

**Comment by MichaelKohler** [comment]
@J0WI forgot about it, sorry.. done now
