### ISSUE TITLE
PHP warning output in event widget

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#78]
In the event widget we currently have

```
Warning: reset() expects parameter 1 to be array, null given in /var/www/html/src/AppBundle/Controller/DefaultController.php on line 45
```

This is probably due to no scheduled events. We either need to fix that (preferred) or at least make sure that it won't show in the widget itself.

![screen shot 2016-08-09 at 23 45 06](https://cloud.githubusercontent.com/assets/330324/17534836/874f2578-5e8b-11e6-9d8f-9e4fd78789c6.png)

**Comment by freaktechnik** [comment]
[Good first bug]: Need to update the condition when the ical is parsed to require one more line on https://github.com/mozillach/mozilla.ch/blob/master/src/AppBundle/Controller/DefaultController.php#L110 as it seems remo has changed outputformat.
