### ISSUE TITLE
Set HSTS

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#83]
We currently don't set an HSTS header, even though the site is only reachable over HTTPS. Is this something we should set ourselves, or should the router from community infra insert it, since we technically only expose an HTTP server?

@flamingspaz is this something we should do on our side?

**Comment by flamingspaz** [comment]
We're working on that on our side. Since all of the sites support HSTS it's easier for us to do this on the load balancer side.

The bug for this is https://bugzilla.mozilla.org/show_bug.cgi?id=1290410

**Comment by freaktechnik** [comment]
Thanks for the fast feedback, makes sense that it would be done on your side, since you control the cert and can actually estimate the duration it should be cached.
