### ISSUE TITLE
Replace "Get in touch"

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#86]
Let's replace the link and icon of "Get in touch" with a link to https://discourse.mozilla-community.org/c/communities/switzerland . Not sure what we could use as icon though.

![screen shot 2016-10-07 at 14 47 49](https://cloud.githubusercontent.com/assets/330324/19190383/86aaeb76-8c9d-11e6-9c3e-05e7a963c7ad.png)

**Comment by freaktechnik** [comment]
that's already done. (in theory)

**Comment by freaktechnik** [comment]
duplicate of #77

**Comment by MichaelKohler** [comment]
eeeh, right.. sorry :(
