### ISSUE TITLE
Add Tile content

### ISSUE THREAD

**Issue by MichaelKohler** [mozillacommunitych/mozilla.ch#9]
- [x] Upcoming Event
- [x] Get Involved
- [x] Past events
- [x] Follow us on twitter
- [x] Download Firefox
- [x] Social Media stream
- [x] Some people's pictures from mozillians.org
- [x] Campaign tile
- [x] Help
- [x] Mail (info at mozilla.ch?)

Random tiles: (to fill the space)
- [x] Firefox OS Apps from MozillaCH in Marketplace (Weight: 2)
- [x] Firefox OS (Weight: 1)
- [x] Privacy (Weight: 2)
- [x] Independent (Weight: 2)
- [x] Webmaker (Weight: 1)
- [x] Firefox Hello (part of the comaign tile, nothing else needed)
- [x] Dev Edition (Weight: 2)
- [x] Firefox Android (Weight: 1)
- [x] Marketplace (Weight: 1)
- [x] Gearstore (Weight: 2)

**Comment by jviereck** [comment]
> Follow us on twitter

Done as part of the embedded twitter feed.

**Comment by freaktechnik** [comment]
![p_20150329_004412](https://cloud.githubusercontent.com/assets/640949/6883769/c31f907e-d5c5-11e4-91eb-fd7d558dcf00.jpg)

**Comment by freaktechnik** [comment]
The follow us tile content is currently cut off in french. I'm not sure if we want that text size. Or do we want dynamic scaling?

**Comment by J0WI** [comment]
The twitter feed should not be embedded as an iframe for privacy reasons.

**Comment by J0WI** [comment]
Public API from marketplace: https://firefox-marketplace-api.readthedocs.org/en/latest/topics/search.html

**Comment by freaktechnik** [comment]
Should get involved link to the get involved section below or http://mozilla.org/contribute? I'd assume the Help tile will link to http://support.mozilla.org (support and mail also need l10n).

**Comment by MichaelKohler** [comment]
just a #ID link to the section below should be enough

**Comment by freaktechnik** [comment]
Using the anchor doesn't work fully, as the page gets reloaded on click (because of the target="_self" which it needs because we have a target="_blank" in the base?"), which works until the reflow for the grid has happened, and causes the page to scroll down in the viewport (as the grid takes up less space).

**Comment by freaktechnik** [comment]
I've added a string for the next event tile for the case that no event is planned. As a heads up: the page now uses the intl module to get the name of the month in the current language (not sure if that module works with rm^^), so you might have to add that to your php server.
EDIT: yup, rm causes a timeout.
EDIT2: it seems mozilla.org translates the month in the big date, but uses the english name in the date.
EDIT3: German is probably a better fallback... waht do you think @gion-andri ?

**Comment by J0WI** [comment]
For our own twitter widget:
https://cdn.syndication.twimg.com/widgets/timelines/581826491673128960

**Comment by freaktechnik** [comment]
@J0WI colin already added a twitter library, there's just no template and controller to generate the actual widget, since he agreed that the widget from twitter is enough.

**Comment by J0WI** [comment]
@freaktechnik see https://github.com/mozillacommunitych/mozilla.ch/issues/9#issuecomment-87416118

**Comment by freaktechnik** [comment]
@J0WI what I meant, si that we dont' ahve to worry about the actual twitr API endpoints as we have a twitter lib: https://github.com/mozillacommunitych/mozilla.ch/blob/master/src/AppBundle/Command/TwitterFeedCacheCommand.php (though this isn't renderable, if I understood the symfony docs correctly, so we'd need some code to make a rendering twitter feed)

**Comment by J0WI** [comment]
How do you think about other tile content like https://www.mozilla.org/privacy/tips/ or https://www.mozilla.org/firefox/independent/?

**Comment by MichaelKohler** [comment]
Sure, feel free to create a tile :) I don't think there is any existing? But we can adopt one and just change the color or something. Nice idea! I could even imagine to have this as non-random (persistent) tile

**Comment by MichaelKohler** [comment]
"Some people's pictures" is almost done it seems, looks nice! Though there are still two Gravator pictures that don't get replaced.

**Comment by freaktechnik** [comment]
@MichaelKohler: have tried reload cycling? Basically it displays the switzerland group's gravatar pictures with a random offset, so those two tiles contain the picture of someone without a gravatar set. Further we need to define the link they point to.
EDIT: also, do you want random tiles to have something like a rotation?

**Comment by MichaelKohler** [comment]
Could we take another person to make sure we almost have pictures? So everybody who hasn't a gravatar picture wouldn't show up. That would be fine with me until we figured out how to get the picture from Mozillians.org.

Regarding rotation: not necessarily, but would be great. We have more tiles than space anyway so we have some kind of rotation anyway.

**Comment by colinfrei** [comment]
We don't currently check if a gravatar picture exists, we just call up the image which has the built-in fallback. Could probably check that as well, though we'd have to decide what to do then, to make sure the same person doesn't show up twice.

**Comment by MichaelKohler** [comment]
I just updated the random tiles with an "weight", if we want to implement that.

**Comment by freaktechnik** [comment]
We could alternatively use unique gravatar default pictures instead (identicon, mosnterid, wavatar, retro).

**Comment by MichaelKohler** [comment]
Well, that still would look weird. I'd really like to have all faces ;)

**Comment by MichaelKohler** [comment]
I think "Firefox OS Apps from MozillaCH in Marketplace" is actually a really strong tile too. Maybe we could put it as 2x1 below "Download Firefox" and show it all the time? Then we'd also don't have the problem regarding the 1x1 "random" tile.

Then we would have 2 2x1 tiles left to show the rest of the "optional" tiles randomly.

What do you think?

**Comment by MichaelKohler** [comment]
Working on the 1x1 Mail tile now.

**Comment by MichaelKohler** [comment]
I just deleted the Donation Tile from the list since we have enough otherwise. We still have the Donate link in the header. And for the end of year fundraising campaigns we can use the campaign tile.

**Comment by MichaelKohler** [comment]
Let's close this one and open new issues for issues with different tiles.
