### ISSUE TITLE
Avatar tiles not fully randomized

### ISSUE THREAD

**Issue by freaktechnik** [mozillacommunitych/mozilla.ch#90]
Currently two avatars are always displayed twice. The code needs to be double-checked and if that's not the issue look into twig caching posing a potential issue.

**Comment by MichaelKohler** [comment]
Not for me, can you reproduce on different devices?

**Comment by freaktechnik** [comment]
Seems to work from my office PC. However on Saturday both me and @annevk had this phenomenon.

**Comment by annevk** [comment]
I'm no longer seeing it either.

**Comment by MichaelKohler** [comment]
Closing since this can't be reproduced anymore.. feel free to reopen once you could reproduce it again.
